version: '3.8'

services:
  jupyter:
    build: .
    container_name: dsdojo3-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
      - JUPYTER_ENABLE_LAB=yes
    working_dir: /workspace
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    stdin_open: true
    tty: true
